"""Git worktree isolation for write tasks."""
import subprocess
from pathlib import Path
from datetime import datetime

def create_worktree(repo_dir: Path, task_slug: str) -> dict:
    branch = f"cs/{task_slug}/{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    worktree_dir = repo_dir / ".claude-scheduler" / "worktrees" / task_slug

    if worktree_dir.exists():
        subprocess.run(["git", "worktree", "remove", "--force",
                        str(worktree_dir)], cwd=str(repo_dir),
                       capture_output=True)

    worktree_dir.parent.mkdir(parents=True, exist_ok=True)

    subprocess.run(
        ["git", "worktree", "add", "-b", branch, str(worktree_dir)],
        cwd=str(repo_dir), check=True, capture_output=True)

    return {"worktree_dir": str(worktree_dir), "branch": branch}

def cleanup_worktree(repo_dir: Path, worktree_dir: Path, branch: str,
                     keep_branch: bool = False):
    subprocess.run(["git", "worktree", "remove", "--force",
                    str(worktree_dir)], cwd=str(repo_dir),
                   capture_output=True)
    if not keep_branch:
        subprocess.run(["git", "branch", "-D", branch],
                       cwd=str(repo_dir), capture_output=True)

def has_changes(worktree_dir: Path) -> bool:
    result = subprocess.run(
        ["git", "status", "--porcelain"], cwd=str(worktree_dir),
        capture_output=True, text=True)
    if result.stdout.strip():
        return True
    result = subprocess.run(
        ["git", "log", "--oneline", "HEAD", "--not", "--remotes", "-1"],
        cwd=str(worktree_dir), capture_output=True, text=True)
    return bool(result.stdout.strip())

def push_and_create_pr(worktree_dir: Path, branch: str,
                       task_name: str) -> str | None:
    result = subprocess.run(
        ["git", "push", "-u", "origin", branch],
        cwd=str(worktree_dir), capture_output=True, text=True)
    if result.returncode != 0:
        return None

    result = subprocess.run(
        ["gh", "pr", "create", "--draft",
         "--title", f"[claude-scheduler] {task_name}",
         "--body", f"Automated changes from scheduled task: {task_name}\n\n"
                   f"Branch: `{branch}`\n"
                   f"Generated by claude-scheduler"],
        cwd=str(worktree_dir), capture_output=True, text=True)
    return result.stdout.strip() if result.returncode == 0 else None
